### ISSUE TITLE
Unhappy with name "Consolidate"

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#1]
I am unhappy with the name of the consolidate command, and its short description.  Neither seem to indicate exactly what the command does from the users point of view. It is sort of an internal clean up thingy in a way. From the users perspective it does one thing only I think: it deletes local change history. Is there a better name and description? Can the concept be eliminated or automated behind the scenes?

Since by definition, Acre Desktop is local, perhaps a more apt name is PurgeChangeHistory, and description would be "Permanently delete local change history"?

**Comment by norberturkiewicz** [comment]
If memory serves me right, consolidate used to delete the change files and update the codefile of a local project.  The codefile is no longer the master.  Maybe this is more of a local cleanup operation?

**Comment by PaulMansour** [comment]
Yes, you are correct, but it still has to be done. Is there any way to automate this? Presumably when one is committing in git, you want to purge the local history. If one is just using Acre Desktop by itself though, I don't think we can say when the user wants to clear out the change history. Will need Phil's 2 cents.

**Comment by norberturkiewicz** [comment]
My git project has a .gitignore set to omit the .acre folder from any uploads.  All the changes are local.  I added this file to the root of Acre-Desktop.  

I regular workflow I'll probably forget they even exist.

**Comment by PhilLast** [comment]
I think it's reasonable that the user should be able to decide when to do this. If he's committed (pushed?) stuff up to git/github/SVN then the latest versions in the change files ought to be in the codefile and the change files deleted. Otherwise the project will just continue to grow in size as changes are made as ]ED, ]Undo and ]Redo are now all non-destructive.

**Comment by PhilLast** [comment]
I think it's reasonable that the user should be able to decide when to do this. If he's committed (pushed?) stuff up to git/github/SVN then the latest versions in the change files ought to be in the codefile and the change files deleted. Otherwise the project will just continue to grow in size as changes are made as ]ED, ]Undo and ]Redo are now all non-destructive.

**Comment by PhilLast** [comment]
Suggestions as to what to call it?

**Comment by PaulMansour** [comment]
I would call it PurgeChangeHistory. I can't think of a better name that describes what it does conceptually for the user. 

The "codefile" is an internal optimization, and could easily disappear in the future. I purposely make no reference to it in the documentation. The  **change history** however is very much something that concerns the user, though the implementation details of  "change files" should not.

Not sure weather this should be called "change history" or "Local change history" or "local history" or what.  By definition, everything about Acre Desktop is local, so the word is a bit redundant. 

It is interesting to contemplate what happens if the change history is not purged on the same schedule as SCM synchronization. It is going to accumulate changes by other users downloaded from the SCM, and changes in the ops sys too.  I think this is fine, and perhaps very useful.

**Comment by PaulMansour** [comment]
I'm leaning towards simply:

]acre.PurgeHistory

I think adding in "local" or "change" doesn't make it any better, just longer.

**Comment by PaulMansour** [comment]
PurgeHistory it is.
