### ISSUE TITLE
Add "Init" function call to acre config

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#108]
We already have a kind of `⎕LX` function in acre. That function is executed after acre has done its job.

I am proposing an additional `Init`. If that is found in the acre config file it should be executed _before_ acre does anything in terms of opening a project,

That would allow to load stuff, for example via a packet manager, the project to be opened depends on, It might be a useful feature for other purposes as well.

**Comment by PhilLast** [comment]
Initial thoughts:
Obviously what I'm describing is the way acre happens to be at 2018-07-25 10.04 and none of it is set in stone.

0. checks that the path leads to a project, sets up the project data space (not the project space), and reads in and evaluates the config file if it exists.
1. checks that the project is not to be tracked inside another tracked project. 
2. opens the project dependencies.
3. checks that none of the dependencies has usurped the target project space.
4. creates the project space and loads the project code.
5. executes `startup` in the project space if the project is to be tracked and is the top level project opened by `⎕SE.UCMD` rather than as a dependency of another project.

`init` could not be executed before **0.** Were it executed any time before **3** there is still a chance that acre could give up at a later stage.

At what point do you imagine _before acre does anything in terms of opening a project_?

Would `init` be executed conditionally with the same provisos as `startup`?

In what way would this differ from enhancing the dependency code to recognise "packages" vs "projects" along lines proposed by @PaulMansour and @e9gille?

**Comment by aplteam** [comment]
I was intrigued by the idea to have that `Init` function available which would allow me to do it one way now and a different way later. 

However, I realize that I can execute as well my own user command `]foo` doing als the prep upfront and then call ]acre.OpenProject, therefore I withdraw my request,
