### ISSUE TITLE
Manually creating a folder

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#110]
If , in the OS, you manually create a folder without a case-code, copy in some functions (with case codes) and then open in Acre, no problem. However if you then change a function, a new folder is created with the proper case code and that function is put in it. In other words, Acre is not renaming the folder on open. Should it?

**Comment by e9gille** [comment]
Sounds to me like it should.

**Comment by PhilLast** [comment]
Turns out it could be quite complicated because of the `sourcereg` file, used if `keephistory` is on, that keeps filenames, and dates. Currently used for two purposes. To recognise new, changed and deleted files and to allow acre to write a changed item back to the same file even if slightly wrongly named. Now files are being renamed that aspect is largely redundant.

Currently if `keephistory` is on and a file named in `sourcereg` is deleted that represents an item that has already been changed the `.change` file is renamed to `.delete`. If `keephistory` is off or the item has not been changed then acre ends up knowing nothing about it.

I could recognise new and changed files if `OpenProject` and `Refresh`, or the subfunction that both call, were to save the date.time it last ran as they will then have a date.time after that saved.

This will preclude the creation of change files by acre for files copied into folders which have a changed date earlier than acre's, 'though they would obviously still be read in and change files would be created if changed subsequently.

So removing `sourcereg` entirely is not difficult **_if there are no objections_** to losing also the recognition of deletions from and copies to APLSource in some circumstances. But it affects only history in rather unlikely cases and makes the renaming of files and folders much simpler.

**Comment by PaulMansour** [comment]
> For some reason I seem to be in a position where I can't even use the facilities provided by v16 which I've only recently acquired because acre has to remain compatible with Fire and that has to support v15.

Egads, can we not do that? Acre has what, 7 users tops? Let's not make work.

**Comment by aplteam** [comment]
I need ti support 15.0 in accordance to my agreement with Dyalog regarding all members of the APLTree project and the APL-cation project.

Since so far the only person that has ever contributed to any of those projects is Gil I don't see how it would pose a problem if acre would require at least 16.0

The APLTree and APL-cation projects as such can still support 15.0

**Comment by PhilLast** [comment]
Bug fixed possibly without using anything that wasn't available in v15 after all.
