### ISSUE TITLE
Error opening projects !!!Not fixed .class

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#111]
`Dyalog APL/W-64 Version 17.0.33755
Unicode Edition
Wed Aug  8 13:33:04 2018
      ]openproject
 Acre  4.5.0.013  2018-07-30

      ]openproject   c:\github\carlislegroup\cas7
Opening from c:/github/carlislegroup/AcreTools/
 to #.CarlisleGroup.AcreTools
Please wait - Reading 62 files from c:/github/carlislegroup/AcreTools/APLSource/
Opening from c:/github/carlislegroup/Rumba/
 to #.CarlisleGroup.Rumba
Please wait - Reading 540 files from c:/github/carlislegroup/Rumba/APLSource/
Opening from c:/github/carlislegroup/CASFile/
 to #.CarlisleGroup.CASFile
Please wait - Reading 35 files from c:/github/carlislegroup/CASFile/APLSource/
Opening from c:/github/carlislegroup/TCGUtilities/
 to #.CarlisleGroup.Utilities
Please wait - Reading 23 files from c:/github/carlislegroup/TCGUtilities/APLSource/
Opening from c:/github/carlislegroup/CAS-File-Server/
 to #.CarlisleGroup.CFS
Please wait - Reading 114 files from c:/github/carlislegroup/CAS-File-Server/APLSource/
!!! Not fixed .class #.CarlisleGroup.CFS.v1.Operations.PostExpression
Opening from c:/github/carlislegroup/CASDataModels/
 to #.CarlisleGroup.CASDataModels
Please wait - Reading 18 files from c:/github/carlislegroup/CASDataModels/APLSource/
Opening from c:/github/carlislegroup/cas7/
 to #.CAS
Please wait - Reading 9930 files from c:/github/carlislegroup/cas7/APLSource/
* Command Execution Failed:                                          
!!! Not fixed .class #.CarlisleGroup.CFS.v1.Operations.PostExpression
`

When I run openproject again, in place, it works.

**Comment by PhilLast** [comment]
I assume that if you **)CLEAR** before the second attempt it still doesn't work.

Normally if something won't fix it's because its definition is invalid. In this case, because it works subsequently, it probably means that a field or property setting is missing something the first time that's there the second time around.

In this case class *CFS.v1.Operations.PostExpression* in **CAS-File-Server** may require something currently brought in after it,  possibly something from **CASDataModels**.

The status window might offer a clue.

**Comment by norberturkiewicz** [comment]
Changing the load order fixed the issue.

Maybe a suggestion message in the session?
