### ISSUE TITLE
]editarray name1 name2 does not work

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#114]
Although `]EditArray` seemingly accepts more than one name it opens only the first one.

**Comment by PhilLast** [comment]
```
      ]editarray #.path.item -h
 Edit array in tracked project. In APLAN if not regular text.
 Syntax: ]acre.EditArray item
```
The above could be changed to emphasise the singular as "Edit _an_ array ...". 

The calling framework passes appropriate arguments to the command without count. The command *could* go so far as to add a new message and refuse to do anything if it got more than one or it could continue to do what it does now but issuing a message such as "editing first item only" in passing.

The reason I decided to treat only one is because it invokes the editor differently for `.array` as opposed to `.charlist`, `.charmat` and `.charstring`. The former is modal as it must decode the edited, encoded value whereas _regular_ text arrays can be handed off to the native editor directly.

The existence of this command is mainly for my own convenience as I've been using it for some while. There is no implication that it even approaches the functionality of the supplied `]array.Edit` provided by David Liebtag.
