### ISSUE TITLE
CharMat with UCS 13 10 does not get fixed properly

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#115]
)clear
clear ws

  )ns test
#.test
      )cs test
#.test
      CrLf←⎕ucs 13 10    

      ]createproject c:\temp\crlftest  #.test
Added script "quadVars"
#.test
    ⎕ucs  #.test.CrLf
13 10
      )off
Dyalog APL/W-64 Version 17.0.34139
Serial No : 123456
Unicode Edition
Thu Sep  6 11:06:02 2018
      ]openproject c:\temp\crlftest  
 Acre  4.5.2.017  2018-08-11
Opening from c:/temp/crlftest/
 to #.test
Please wait - Reading 2 files from c:/temp/crlftest/APLSource/
#.test
    ⎕ucs  test.CrLf
13 13

**Comment by PhilLast** [comment]
Oh yes. If it were any other array than a CharMat, CharString or CharList it would be OK because APLAN encodes each of ⎕UCS(⍳32),133 160 as '⍞', 4 hex digits. So ⎕UCS 13 10 would be '⍞000D⍞000A'. The same technique is available for any char for users editing files. But CharMat and CharList are presented as-is with one row or string per line in the file. CharString is separated into file lines on ⎕UCS 13 but other chars are just themselves.

I _could_ encode any of them as APLAN if they contained any of the above apart from ⎕UCS 13 in a CharString. That would certainly be the easiest solution.

**Comment by norberturkiewicz** [comment]
Lot's of syntaxes use \r\n for these two characters.  Maybe we should encode the handful of special characters along these lines...

**Comment by PhilLast** [comment]
Maybe. But pro-tem I have amended the `nameClass` function to classify _any_ text array as `.array` (or `.aplan`) that contains `⎕UCS 10` and any array that would otherwise be classified as `.charmat` (or `.aplm`) but contains `⎕UCS 13`. The current encoding system has been in place since the inception of Acre-Desktop.

**Comment by PhilLast** [comment]
The change mention in previous post was not released. The newAPAN version with the new \r,\n escaping _should_ settle this issue.

Please reopen ifnot
