### ISSUE TITLE
]ACRE.LogLevel command to control messages in session

### ISSUE THREAD

**Issue by e9gille** [the-carlisle-group/Acre-Desktop#126]
Yesterday it occurred to me that I have happily accepted that Acre reports every successful save event to the session. I liked it at first as it confirmed my expectations. However, I don't expect to see that every time I fix a function without Acre, so I am now questioning the reporting altogether.

If there are no bugs (in Dyalog or Acre) I would expect Acre to save my changes to file on fix. The default should therefore be that I see no messages from Acre. If I lose my changes because of a bug in either tool, I would try to isolate the source of the issue and get it fixed.

To aid my debugging I may want to set the log level. This could be as simple as an `on/off` switch or with discrete levels (`info`, `warn`, `error`).

**Comment by PhilLast** [comment]
The `-messages=` modifier is available on all commands.
It is 'On' by default and can be set to 'Off' or to a global name (starting in '#.').
'Off' suppresses all messages 'though note that all commands actually return a result of some kind irrespective of any messages.
If it is a name there are three possibilities.
If the name has no referent it will be created as a list of any messages that would have been displayed.
If the name represents an existing list messages will be appended.
If the name is that of a function it must be monadic or ambivalent and return a result which will be absorbed but ignored. It will be called each time one or more messages are issued.
If not 'Off' or a name it remains 'On' by default.

The modifier must be applied to each command where messages are required to be off or diverted and reverts to default for the next command.

* __It _could_ be enhanced alternatively to be a session level switch and to filter messages by some categorisation.__

Not changed for many months when it was changed _from_ session to command level it is currently under further development to incorporate the new _popup_ messages that were added to handle lists that otherwise would drown the session log and will be subject to the same controls.

**Comment by e9gille** [comment]
> Not changed for many months when it was changed from session to command level

I probably missed the conversation that led to this, but I found yesterday that the `Saved:` messages can't be turned off because they are not generated by a command. It would be good to be able to configure this on a session level.

I have seen the options offered by `showMsg` and it is very clever the way it is implemented, _but_... when do you ever want to provide a name? The only reasons I can think of is:

1. If name is a list it is to prevent messages from flooding the session, but the developer wants to be able to inspect it (perhaps for the purpose of running test cases and checking results).

1. If it is a function I can imagine it being used to write to file or to a GUI window. But if it is a function, where is it defined and stored? If I open an acre project I need to provide the function name as part of the command. Do you envisage developers will create their own user commands that wrap Acre commands?

I would have thought logging to `[file | session | window]` as 3 options with `[ on | off ]` and potentially categories of messages to log should be more useful and cover most scenarios.

**Comment by aplteam** [comment]
I am very happy with the "name" options: it's used by the test cases.

**Comment by e9gille** [comment]
> I am very happy with the "name" options: it's used by the test cases.

Sure, but presumably you only need one of those for test cases. In addition, an alternative (writing to file) should also tick your box?

**Comment by aplteam** [comment]
It would, but a variable is so much more convinient.

**Comment by PhilLast** [comment]
> I would have thought logging to [file | session | window] as 3 options with [ on | off ] and potentially categories of messages to log should be more useful and cover most scenarios.

You may be right but no-one asked for it before. Can you offer an example of the syntax you envisage?
```
]acre.command args -m=???
```

**Comment by e9gille** [comment]
First of all, I still don't know why it was changed from session to command level. Is there a reason?

I am suggesting it becomes a session level setting (potentially with a user level configurable default):
```
]acre.log [ 'file://acre.txt' | window | session | off ] [ -level=info|warn|error ]
```

If no args return current setting.

> It would, but a variable is so much more convinient.

But only if you are running test cases. As a user I would find a log file that survives a potential crash much more useful.

**Comment by PhilLast** [comment]
> First of all, I still don't know why it was changed from session to command level. Is there a reason?

Because testing was the only reason it was created in the first place and it was deemed to be more useful for testing that way. I doubt before this issue it's ever been considered by anyone in any other context.
> I am suggesting it becomes a session level setting (potentially with a user level configurable default):

> ]acre.log [ 'file://acre.txt' | window | session | off ] [ -level=info|warn|error ]

As I said earlier, currently balancing popups with messages in terms of their controls. We gave the `-messages` modifier command scope deliberately so that it would fall back to the default.

I'd like to consider which is more possible or desirable between: adding your requirement to the existing modifier; and replacing the modifier with your requirement as another command & adding the modifier scope to that. 
I'd rather not end up with both. Then again if for any reason, testing or otherwise, it's necessary to turn off messaging for a single command we don't want to have to run three commands instead of one.

Perhaps it's possible to devise a syntax that's applicable to either but where the `-messages` modifier has command scope and maybe a change of name and the logging command has session scope.

**Comment by e9gille** [comment]
Right, so to summarise:

* Kai requested a way to capture messages to simplify the writing of test cases for Acre
* Diane requested a list of warnings/errors when first converting a project to Acre
* I'd rather not see any info messages at all in the session. Specifically messages that are generated dynamically and not as a result of executing a command.

**Comment by PhilLast** [comment]
Might all requirements be satisfied if instead of a plethora of options and or commands about messages in the session (or not) and specification of destinations (or not) and suppression (or not) and whatever else - we had a single, rolling, window whose content is directly accessible both manually and under program control where all messages were prepended and whose only option was maximum length?

**Comment by PaulMansour** [comment]
Sounds good to me Phil.  The whole things seems overly complicated at this point. Drastic simplification is in order. I would even get rid of the max length option and just make it something reasonable.  Zero options.

**Comment by PhilLast** [comment]
Almost ready.

**Comment by PaulMansour** [comment]
Obsolete
