### ISSUE TITLE
array may require attention after acre update

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#129]
@PhilLast  can you assist with this error?

!!! Not fixed .array #.CAS.RTF.STYLEMACROS.BOLD
!!! Not fixed .array #.CAS.RTF.STYLEMACROS.ITALIC
File: .../RTF-7/STYLEMACROS-7ff/BOLD-f.array may require attention.
File: .../RTF-7/STYLEMACROS-7ff/ITALIC-3f.array may require attention.
* Command Execution Failed:
!!! Not fixed .array #.CAS.RTF.STYLEMACROS.BOLD
!!! Not fixed .array #.CAS.RTF.STYLEMACROS.ITALIC

[STYLEMACROS-7ff.zip](https://github.com/the-carlisle-group/Acre-Desktop/files/2600864/STYLEMACROS-7ff.zip)

**Comment by PhilLast** [comment]
I assume the files represent the charstring "\b" standing for BOLD and "\i" for ITALIC in RTF notation.

Acre has renamed them to .array from .charstring because each one evaluated as a scalar char.

This is because version 4.8.0 added the "backslash" escape encoding of control chars "\r" "\n" &c.. I assume you didn't run the _Fixchars_ command that was also a part of release 4.8.0.

If these two files are the only casualties of not having run it, the easiest and safest way to fix it is _not_ to run ]Fixchars but to edit both files in the OS, remove any quotes, add another backslash in front making the entire content the three chars \\b and \\i and rename to .charstring again. Next time you ]openproject on it the "\b" and "\n" will be restored.

**Comment by norberturkiewicz** [comment]
The manual adjustment did the trick.
