### ISSUE TITLE
Wiki is missing information on how/when variables are tracked

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#130]

**Comment by aplteam** [comment]
> The wiki does not mention the tracking of arrays specifically because in this respect they are treated identically to other types.

It should. As it should mention that something that is `⎕FIX`ed or `⎕FX`ed or assigned (`Hello←{'word'}`) is **not** tracked because for somebody new to APL this might well be a surprise. For that reason I suggest a page like "What's tracked".

And maybe it's an idea to ask Dyalog to actually include all ways to define a function, but certainly not assignments to variables.

**Comment by e9gille** [comment]
Maybe it was missed in the Link API, but to summarise the reasoning around arrays we said:

1. Acre currently creates a new file if you edit a character array variable while tracing, this is likely unwanted.
1. Link and Acre only trigger on editor fix events, so at the moment it is only a problem for the 3 char types supported by Acre.
1. Assuming that arrays stored in source are some sort of constants, it seems sensible to require that they get added explicitly rather than automatically. When migrating code into Acre for the first time it might be important to include arrays.

The suggested solution was to only track arrays if they originate from file. By calling `]SetChanged` or `]EditArray` you explicitly ask for something to be tracked.

**Comment by PhilLast** [comment]
>> @PhilLast  The wiki does not mention the tracking of arrays specifically because in this respect they are treated identically to other types.

> @aplteam It should. As it should mention that something that is ⎕FIXed or ⎕FXed or assigned (Hello←{'word'}) is not tracked.

So _not_ mention the tracking of _arrays_ specifically but _all items_ changed or created elsewhere than in the editor.

**Comment by PhilLast** [comment]
> @e9gille The suggested solution was to only track arrays if they originate from file. By calling ]SetChanged or ]EditArray you explicitly ask for something to be tracked.

I'm still wondering when, where and by whom these discussions, solutions and decisions were made already to be mentioned in the _gap analysis_ prior to the _hackathon_. I think not by the acre/Carlisle team and not in this forum.

But I do see the sense in the not tracking newly created items in some respects because I often clone functions to make experimental changes and finally decide which version I want. If the new then I rename that to the original and otherwise not. But either way I have to `]erase` the other because acre has automatically tracked it. Now here I'm referring to functions.

If the starting of the tracking of arrays is to be on-demand should it not apply to all items?

**Comment by e9gille** [comment]
> I'm still wondering when, where and by whom these discussions, solutions and decisions were

Apologies, I realise I have to be careful not to use the word "we" and "decided" as generously as I have. Note that I have been in many conversations with individuals and organisations and sometimes lose track fo who said what.

I believe the issue first was raised during an internal demo/review in Optima. I then discussed it with Morten. It was put into the GAP analysis so it wouldn't get forgotten about and seeing as we were about to meet in person, I hoped to discuss it with you Phil in Bramley.

I don't mean to sound like I make the calls here. I should have been more specific and expressed myself better. I'll keep that in mind for the future.

> If the starting of the tracking of arrays is to be on-demand should it not apply to all items?

No, I don't think so. Arrays may be constants or variables it is unclear, other items are typically source code. Ideally it should distinguish local names and ignore them, but if that is not an option I think it makes sense to treat at least arrays more carefully.

**Comment by PhilLast** [comment]
I should have no objection to this change if a Fix event's occurring on a previously unsaved object caused acre to put up a modal msgbox asking the question whether or not to save it.

I should hate to have spent spend time creating a text item and find at the next session that I'd thrown it away.
