### ISSUE TITLE
On variables

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#161]
This came to light only because acre detected a problem with the same name used twice: it was used once for a char string and once for a vector of char strings.

That happened because I was tracing through code and tried to amend a variable so that I can fire up Ride with certain command line parameters. For that I used at least once an assignment and several times the editor.

What I forgot was that acre saves variables! When I changed the local variables from a `⎕UCS 10` separated text vector to a vector of text vectors I caused acre a headache. And myself...

I propose to investigate any variable that is changed in the editor with `⎕STATE`. If that variable turns out to be localized on some level then acre should **not** save it.

**Comment by aplteam** [comment]
I should have mentioned that I investigated all my projects and found quite a number of variables to be part of them when I actually expected to see very few indeed. They are just waiting there for an opportunity to cause trouble!

**Comment by e9gille** [comment]
I've raised this issue before and suggested that the char* types only update existing files. It would require an explicit action via the API to first save one to disk for it to be subsequently tracked.

Similarly one could argue that createproject by default doesn't write them to disk unless specifically requested via a switch.

**Comment by norberturkiewicz** [comment]
> I've raised this issue before and suggested that the char* types only update existing files. It would require an explicit action via the API to first save one to disk for it to be subsequently tracked.
> 
> Similarly one could argue that createproject by default doesn't write them to disk unless specifically requested via a switch.

This sounds reasonable but I would also consider a warning that this variable is not managed by acre.

**Comment by aplteam** [comment]
I now agree with Gil.

**Comment by PhilLast** [comment]
Implementing this. A couple of options.

Gil mentions a switch on `]CreateProject` (`-vars=on/off` - dflt='Off' ?). Now this couldn't practically be per variable within the confines of a single call to a user command. So the switch would have to cover all vars existing anywhere within the project space-tree at creation time.

I see no reason to prevent `]SetChanged` from saving on request and for `)ED`, `⎕ED` and `]EditArray` to continue to save vars already saved.

But I also feel that if we do not allow an option to continue with the _status quo_ it might well result in `]SetChanged` being called more often than the inadvertent saving of an extraneous variable happens at present.

So I'm proposing that the `-vars=on/off` modifier in `]CreateProject` persists as configuration parameter `Vars←'On'/'Off'` such that `Vars←'On'` will leave everything as now and `Vars←'Off'` is as above re. `]SetChanged`, `⎕ED` &c..

Mentioning @PaulMansour because he hasn't contributed to this thread and might like a say.

**Comment by PhilLast** [comment]
See release notes to _Acre 5.0.12+173 2019-04-24 15.20_

As above suggestion of 13 days ago but with `-variables=` and `Variables←` rather than `-vars=` and `Vars←`.

The default being `'Off'` new variables in old projects will not be saved unless `Variables←'On'` is added to the config file 'though existing ones will continue to be saved when edited.

**Comment by PhilLast** [comment]
... and of course by `SetChanged` irrespective of the `Variables` setting.
