### ISSUE TITLE
Functions and operators

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#164]
When one promotes a function to an operator then the next time the project is opened acre will complain that there are two files resulting in different APL objects with the same name. 

That's because if the name in question is `foo` then there is a file `foo.f` and a file `foo.o`.

I managed to run into this already several times, and it is really annoying.

I believe that the benefit of having different file extensions for functions and operators are outweighed by the trouble this causes. It can be eliminated by having just one files extension (`f`) for both, so that's what I am proposing.

I realize that the same problem occurs when one changes a scripted namespace to a class or vice versa, but that it way less likely to happen.

**Comment by PhilLast** [comment]
When @aplteam raised this issue I knew - but I couldn't recall it - that there was a good [pov] reason to distingish them and I remembered this morning when reviewing the wiki regarding [casecodes](https://github.com/the-carlisle-group/Acre-Desktop/wiki/Item-Names-and-File-Names) and [filetypes](https://github.com/the-carlisle-group/Acre-Desktop/wiki/Item-types-and-File-types).

If we have `casecode=On` then function `abc` and operator `ABC`  have their filenames distinguished by _both_ their casecode and filetype: `.../abc-0.aplf` and `.../ABC-7.aplo`.

But even with `casecode=Off` they are still distinguished by their filetype: `.../abc.aplf` and `.../ABC.aplo`.

The likelihood of names differing only by case is unknown so _casecoding_ is rightly allowed to be optional. But both the absolute and differential likelihoods - raised above - of the "promotion" of _function_ to _operator_ and _namespace_ to _class_ are similarly unknown.

With a user base of _less than_ a dozen I think we need more experience to decide the issue.

**Comment by abrudz** [comment]
Clearly the behaviour of APL in the workspace should be mirrored in the directory, so just as editing a function thereby making it an operator removes all trace of the function in the workspace, so too should the .aplf file be entirely replaced by the .aplo file.

**Comment by e9gille** [comment]
I can see why (in Acre) it is difficult to tell if a file should be replaced without inspecting the content, but I agree with Adam.

**Comment by PhilLast** [comment]
OK, I'm fully convinced by that. The information is available at the 
time of change so should be fairly straightforward to implement. I'm 
currently looking at the editor callback to permit alternative SCM 
involvement and intervention but this doesn't necessarily impact that.

But the problem is actually wider than this and this solution will not 
completely rid us of it. If an .aplf is edited such that the content 
represent an operator the next `]openproject` or `]acre.refresh` will 
rename the file to .aplo.

But if another file is introduced either by copying and renaming in-situ 
or by directly copying from another project acre cannot pre-empt the 
decision as to which is preferred by the user. I suspect the same or 
similar problem could rise by switching SCM branches.

**Comment by PhilLast** [comment]
> The information is available at the time change ...

By which I mean ``⎕NC` rather than inspection of content.

And by the way - welcome Adám.

**Comment by PhilLast** [comment]
This was implemented as a part of _Acre 5.0.12+173 2019-04-24 15.20_

Unless multiple files represent items of the same name but different type, changing an item's type in the editor; or by using `⎕FX`, `⎕FIX` or assignment followed by `]SetChanged`; will rename the file to the new type. This uses the same functionality that _"corrects"_ filenames in `]OpenProject` when their contents fix as other than the specified type.
