### ISSUE TITLE
acre help sometimes pretends that name:on is the correct syntax when it is not

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#176]
See `CreateProject`: it states `-variables:on` when it should be `-variables=on`

(I keep typing `-vars` here...)

**Comment by PhilLast** [comment]
This is the help. And in my session, for `]createproject` it gives me
```
Syntax: ]acre.CreateProject folder space -help -casecode:off -variables:off -keephistory:off
```
in the log and for `]?createpoject` or `]createproject -?`
```
]ACRE.CreateProject                                                                          
                                                                                             
 Create a new project                                                                        
 Syntax: ]acre.CreateProject folder space -help -casecode:off -variables:off -keephistory:off
 https://github.com/the-carlisle-group/Acre-Desktop/wiki/Command-Reference#createproject     
```
in the session, including `-variables:off` in both cases but I assume it's the colon you don't like. But if it said either of `-variables=on` or `-variables=off` it would be wrong because this is the help, not an actual call to the function. What are reported here are the defaults and that is the syntax required by the user command interface to define them.

As to `-vars` vs. `-variables` the interface allows unique prefixes but that would be `-var` or `-vari` anyway. I _could_ define another as `-vars` but it would show up on the help with the two as separate options.
