### ISSUE TITLE
json config file: ! Invalid namespace name

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#177]
```
{
    "CaseCode":"On",
    "KeepHistory":"Off",
    "ProjectSpace":"#.CarlisleGroup.CFS",
    "APIFile":"/Assets/openapi-v1.yaml"
}
```

```
]openproject C:\GitHub\CarlisleGroup\CAS-File-Server
! Problem reading C:/GitHub/CarlisleGroup/CAS-File-Server/acre.config
! Invalid namespace name
* Command Execution Failed:


      ⎕se.acreAPI.version''
 Acre  5.1.0+186  2019-05-13  20.45 
```

**Comment by norberturkiewicz** [comment]
It  looks like the error is due to I-beam 7149 being depreciated for []JSON

```
 readConfig←{⍺←⊢ ⋄ cnf←⍵
     rl←Cc⊢ru←{⍵.⎕NL-2}dft←configFields if(0=⊢)⍺⊣0
     0::dft⊣logMsg MS.DB,cnf
⍝     cnf←{_NEXISTS ⍵:⍵          ⍝ new name 2018-11-12
⍝         (⊃'/'UT.pn ⍵),MS.HM    ⍝ try old name
⍝     }cnf
     ~_NEXISTS cnf:dft
     d←nout _NGET cnf                             ⍝ lose blank rows
     r t←0{'⍝'=z←⊃~∘' '⊃⍵:(1+⍺)∇ 1↓⍵ ⋄ ⍺ z}d      ⍝ lose comment rows
     cl←Cc⊢cu←{⍵.⎕NL-2}cfg←t{                     ⍝ actuals
         ⍺='{':7159⌶1↓⊃,/(⎕UCS 13),¨⍵                 ⍝ JSON NOT v14.0!!!
```

**Comment by PhilLast** [comment]
Although a half-hearted decision has been made a number of times to deprecate one or other or indeed all in their turn of the encodings of the config file I haven't actually removed any. Truth to tell I don't understand the reasoning against the flexibility to use whichever feels most comfortable for each user.

Also I suggested not to support JSON beyond Dyalog v16 without the I-beam because it would introduce further complication.

Contrary to all this I have now added `(⍎'⎕JSON')`* to the alternatives for Dyalog v17 and above while leaving the restriction that JSON is not available before the introduction of the I-beam in Dyalog 14.1. And the additional complication was minimal.

(*) The execute of the string is to avoid the problem that if the acre.dws is saved in a version prior to 17.0 the token `⎕JSON` will continue to engender a SYNTAX ERROR even in 17.0 and above. 

Available next commit after testing.

**Comment by PhilLast** [comment]
A word about the apparent oddity of _"Invalid namespace name"_ following the failure to decode the file. Such failure is currently treated as though there were no file existing.

If there is no config file or if it doesn't contain a specification for `ProjectSpace` the project space defaults to the last node name of the project folder. 

In this case that name is _"CAS-File-Server"_ which is not a valid APL name.

The same problem arises during a number of the test-cases where an invalid config file combines with the file-name being reflected in the name of the test function itself 'though in those cases the space name is not invalid so much as already being in use as a function.

This is an explanation not a justification. A remedy will be discussed in another issue.
