### ISSUE TITLE
How to identify reason for "Cannot rename..." error?

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#178]
```
Booting C:\GitHub\CarlisleGroup\CAS7\start.dyapp
Please wait - Reading 9768 files from .../CarlisleGroup/CAS7/APLSource
Cannot rename file "C:/GitHub/CarlisleGroup/CAS7/APLSource/WIZ-7/TimeSeries-11/Step-1.aplf" to "C:/GitHub/CarlisleGroup/CA
      S7/APLSource/WIZ/TimeSeries/Step.aplf"
Cannot rename file "C:/GitHub/CarlisleGroup/CAS7/APLSource/WIZ-7/Shell-1/GetUsername-9.aplf" to "C:/GitHub/CarlisleGroup/C
      AS7/APLSource/WIZ/Shell/GetUsername.aplf"
Cannot rename file "C:/GitHub/CarlisleGroup/CAS7/APLSource/WIZ-7/Sampling-1/RANDOM-3f.aplf" to "C:/GitHub/CarlisleGroup/CA
      S7/APLSource/WIZ/Sampling/RANDOM.aplf"
```

**Comment by PhilLast** [comment]
I assume this is still Dyalog v17.0 or v17.1 with a JSON config file. I've made the necessary changes but haven't yet committed them because I was out all of yesterday and have finally got back to work.

If so what is happening is that acre ignores the error and continues as though the file doesn't exist.

If the project has `"CaseCode": "On"`, the default: `"CaseCode":"Off"` will cause acre to attempt to recreate all folders without casecodes and similarly to rename all files into them.

If any such files already exist the rename will fail.

**Comment by PhilLast** [comment]
OK. So it's another reason that it's failing to read the config.

I removed the code that allowed the old filename `acreconfig.txt` assuming by now that everyone would have changed it to `acre.config`. Will re-instate for now.

Also it isn't JSON but APLScript:
```
:Namespace
    CaseCode←'On'
    Open←'CASDataModels' 'Rumba' 'CASFile' 'TCGUtilities' 'CAS-File-Server'
    ProjectSpace←'#.CAS'
    StartUp←''
    KeepHistory←'Off'
:EndNamespace
```
This has _not_ been removed.

**Comment by norberturkiewicz** [comment]
This was a test work in progress project that was running on a pretty old version of AcreDesktop.

**Comment by norberturkiewicz** [comment]
I don't think we need to reintroduce the support.  Maybe a better error message that acre.config is missing?
