### ISSUE TITLE
User exit without left argument

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#183]
The documentation states that anu user exit function must accept a left and a right argument.

However, in case one forgets to specify a left argument acre crashes and the APL session becomes unresponsive:

```
SYNTAX ERROR
callSCM[3] cfg(#.⍎⍣(3∊#.⎕NC exit)⊢exit)fqn old new path
```

I think that's too harsh. acre should figure out and when the function is monadic or even niladic call it accordingly.

Same for the explicit result of the  function: if it does not return a result that should be accepted.

**Comment by PhilLast** [comment]
Brings up the question of what to do next. I've now added error trapping but at the point the error occurs it's necessary to decide whether or not to stay in the editor and/or continue acre's normal processing to write the file. That decision is supposed to be made by the exit function which has failed for whatever reason. We _could_ treat it as if the function didn't exist but it might well have got through half of its process before hitting some file error. The fact that the session is unresponsive at that point is because the editor is stll active and according to dyalog some _external_ process is running:
![image](https://user-images.githubusercontent.com/34437648/59507411-82147f80-8e9a-11e9-9faa-c84bc432731a.png)

But:

> forgets to specify a left argument

is something a developer might do once in any situation. To add complex processing to decide whether that mistake has been made every time the function runs might be considered overkill? If the function is a dfn or specifies `{left}` it can be called dyadically and its arguments ignored.

**Comment by PhilLast** [comment]
We ***could*** allow the editor to fix the item being edited and terminate with a message to the session that the error has occurred but the item has ***not*** been saved.

**Comment by PhilLast** [comment]
***User exit function is currently called after dyalog has fixed the item but before acre has saved it to file.***

as currently defined it takes:
* left arg as a clone of the namespace represented by the config file of the project.
* right arg as fqn, old-value, new-value and file-path of fixed item.

and is expected to return:
* 0 - acre fails to leave editor and does not save to file
* 1 - acre exits editor but does not save to file
* anything else -  acre saves to file

Agreed at go-to-meeting 2019-06-25:
* fqn of exit fn will be specified as argument to a new acre user command **]acre.SetExit** _fqn_ [say] instead of as an entry in the config file.
* acre will call exit fn after saving the edited item to file.
* may be a requirement for _beforeSave_ later.

***matters arising***
* Does this obviate the need for the old & new values in the right argument and the different results?
* Would it be useful if a non-empty result were treated as one or more log-messages?
* Setting the exit fn could also be implemented as an API function **⎕SE.acreAPI.setexit** _fqn_ [say] being easier to call in a startup routine than **⎕SE.UCMD 'acre.setexit fqn'**

**Comment by aplteam** [comment]
> Does this obviate the need for the old & new values in the right argument and the different results?

I think so.

> Would it be useful if a non-empty result were treated as one or more log-messages?

Excellent idea.

> Setting the exit fn could also be implemented as an API function ⎕SE.acreAPI.setexit fqn [say] being easier to call in a startup routine than ⎕SE.UCMD 'acre.setexit fqn'

Yes.

Any errors in the exit function should be trapped, and an according entry should go into the log.

**Comment by PhilLast** [comment]
Noted. Thanks. On to it. Currently working to call new command `]AfterSave` that allows for easy addition of `]BeforeSave` if deemed necessary.
```
      ]aftersave #.new.value
#.old.value
      ]aftersave
#.new.value
      ⎕se.acreAPI.aftersave '#.other.value'
#.new.value
      ⎕se.acreAPI.aftersave ''
#.other.value
```
Default will be `''` at start of session. `]OpenProject` will apply current value to project if not overridden by project config file as `AfterSave←'#.project.specific'`.

Also note Norbert's good idea that a single callback could be tailored to behave differently per project by reference to an ad-hoc variable in the project config.
