### ISSUE TITLE
OpenProject requires target or ProjectSpace in acreconfig.txt

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#19]
Can open a project with only `APLsource` or only `acreconfig.txt`. But if only the former or the latter has missing or null `ProjectSpace` then must supply target as second item in arg.
`]OpenProject path target`

**Comment by PaulMansour** [comment]
In the original doc/spec, I wrote that the ProjectSpace defaults to the ProjectName  which defaults to the last node name of the project folder.  Since we have gotten rid of ProjectName, the ProjectSpace should default directly to  #.{last node name}.  For example, if the project folder is c:\carlislegroup\FlipDB, the project space defaults to #.FlipDB. 

Any reason we don't want to do this?

**Comment by PhilLast** [comment]
None at all.

My mistake. I must have misunderstood something in one out of this plethora of related conversations that seemed to imply that it had been deprecated.
