### ISSUE TITLE
Acre 6.0 V14.0 DOMAIN ERROR: alt←{1↓'#'sep⊃,/'/',¨'.'sep⊃,/'#',¨⍵}

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#199]
Trying to fix a function in a new project.

DOMAIN ERROR
alt[3] alt←{1↓'#'sep⊃,/'/',¨'.'sep⊃,/'#',¨⍵}

      ⍺
0
      ⍵

      ⍵⍵
∇alt
      ⍴⍵
0

**Comment by PhilLast** [comment]
I was surprised you got into acre 6.0 in Dyalog 14.0 at all unless you had the latest build (258 on Aug 31) that fixed #196 .

(I think) I've fixed this locally but have failed to repro the bug because I can't find a way to make the argument to the **alt** function empty under the editor callback which I can only assume is the problem.

What I've done is proofed the expression against DOMAIN ERROR on ( **, /** _empty_ ) that was given an identity of ( **⊂ ' '** ) in 15.0.

Next commit later today.

**Comment by norberturkiewicz** [comment]
@PhilLast  any chance you can push this change?

**Comment by PhilLast** [comment]
Done.
