### ISSUE TITLE
setEnvironment[17] FILE NAME ERROR on ]acre.openproject (first time used)

### ISSUE THREAD

**Issue by e9gille** [the-carlisle-group/Acre-Desktop#200]
First time used on a new PC, acre tries to read a log file from a folder that hasn't been created `....\AppData\Local\acre\`

After creating the acre folder manually, resumed execution fine, but folder is still empty. Not sure if this is still used, but it seems the folder isn't created early enough.

This is with latest build 6.0.1+263

**Comment by PaulMansour** [comment]
Clearly not for first time install only, as I just downloaded 6.0.1 and I get the same problem on a trusty old machine that has been using Acre for a long time. Must be a new bug introduced.

**Comment by PhilLast** [comment]
Right. It seems `⎕NINFO` requires the _folder_ to exist 'though it doesn't seem to mind if the file doesn't.

Changing it now.

**Comment by PhilLast** [comment]
I realised I'm trying to read from the local appdata acre folder rather than the installation folder which is wherever you've chosen it to be. 

The local appdata folder is where it gets created by `buildWsFromSource` in the `build.dws` if you do it yourself.

Single word change. Done.

**Comment by PhilLast** [comment]
Fixed and pushed as `Acre 6.0.1+265 2019-09-06 16:35`

**Comment by PhilLast** [comment]
What this does is to move the target folder from a strict 
```
(2 ⎕NQ'.' 'GetEnvironment' 'localappdata'),'/acre/'
```
to wherever you have installed acre. The default installation is the above suffixed by the folder name `acreXX.X` where `XX.X` is the _Dyalog_ version in which the system is built - current Releases being 14.0.

This means that the default folder now moves down a level in the folder tree. If you had an `acre.log` file already that seems to have disappeared you will find it at the location computed above.

Acre will not attempt to write to the log unless it exists. To create it anew run
`]log file` or `⎕se.acre.Log 'file'`.

Since **Acre 6.0.0+258 2019-08-31 21:51** acre has logged the size of the log file if it exists on starting and will report it also to the session if it exceeds 1MB.
