### ISSUE TITLE
SetChanged saves variables when a namespace is passed as argument

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#218]
The documentation says that `SetChanged` is one of the means to save variables even when the config file reads Variables=off, but I think that should be the case only if a variable is passed as the argument, or part of the argument.

When the argument is a namespace then the config settings should rule whether any variables inside that namespace should be saved or not. 

Currently it is saving all variables as well.

**Comment by aplteam** [comment]
It might be a good idea to add a switch `-vars` in case one wants to save all variables as well.

**Comment by norberturkiewicz** [comment]
If I remember correctly, SetChanged was one of the few way to force a variable to save when it was set to off in the config.  

I'm for the behavior being consistent with the switch.  I would however like a warning that there are times that are not being flagged and tracked in the namespace being SetChanged.

What should happen if you SetChanged on a variable path but it's disabled in the config?  Error and force a switch to override the behavior?

**Comment by norberturkiewicz** [comment]
If I remember correctly, SetChanged was one of the few way to force a variable to save when it was set to off in the config.  

I'm for the behavior being consistent with the switch.  I would however like a warning that there are times that are not being flagged and tracked in the namespace being SetChanged.

What should happen if you SetChanged on a variable path but it's disabled in the config?  Error and force a switch to override the behavior?

**Comment by aplteam** [comment]
I am moaning only about the special case that a namespace is provided as the right argument. 

When a variable is passed to SetChanged then it saves it, no matter what the config file is saying, and that's perfect. If you don't want that, don't do it.

But if I want to save all functions and operators within a namespace but not any variables, then this is currently not possible.

That's why I suggest to change the behaviour so that it's rules by the config file.

**Comment by PhilLast** [comment]
This echoes #211 almost exactly and I don't feel qualified to decide the issue. I'd like an executive decision. But there is one side issue that I'd like clarified.
> However, let's leave this open because at the moment SetChanged is supposed to save variables, but it's not actually doing this with -recursive.

This seems to contradict the whole purpose of the issue but I see no evidence of it.

**Comment by aplteam** [comment]
Seems as if back then there was a problem with variables but not anymore.

**Comment by aplteam** [comment]
I forgot about #211 but run into this again while working on a project. This time is was a variable that was accidentally not localized. I still have the strong feeling that `SetChanged` should honour the configuration settings.

**Comment by PhilLast** [comment]
@PaulMansour Can you decide this one way or other.

Editing a previously unsaved variable only results in its being saved if the **Variables** config setting is **On**.

**SetChanged** ignores the setting and saves everything it's asked to but requires the **-recursive** flag to save all members of a namespace tree.

Kai is asking for the latter situation to be changed such that **SetChanged _nnn_ -recursive** saves all but variables unless **Variables** is **On**.

The matter is discussed at length here and in issue #211.

_Editing a previously saved variable results in its being saved regardless._

**Comment by PaulMansour** [comment]
I'm wondering if we shouldn't get rid of the Variables parameter, and have it be On all the time.  I'm sure way back when I thought it was important to not save variables automatically, but now with Git and they way I review may changes before committing, it seems unnecessary.

**Comment by aplteam** [comment]
I could no disagree more.

Originally I was in favour of saving all variables, and in the early days it did. Gil argued strongly against this, and after a couple of month I realized that he was right: I never forgot to save a variable I wandet to save, but many times I discovered variables that got saved without my intention.

**Comment by PaulMansour** [comment]
I assume saving a variable without intending to happens when you edit a variable that does not exist on disk correct?  And probably a local variable when tracing?  I guess I rarely use the editor to edit local vars. 

I assume the editor has no way of knowing if the var is local?

**Comment by aplteam** [comment]
Yes, it's about local vars. It might be possible to work something out with
⎕STATE but I am not sure how trustworthy that would be these days.

**Comment by PhilLast** [comment]
It's possible to identify locals with a lot of messing about and a fair degree of certainty within tradfns; dfns less so.

But I'm still unsure under what circumstances you might use **SetChanged** on a namespace which contains a currently suspended function. Adding a namespace to a project is something you're only going to do once. It's worth taking a bit of care over it. And if you do make a mistake you can always use **]Erase** or erase its file in the OS.

As to the idea of **SetChanged** never saving even named vars without **Variables←'On'** I'd rather have to erase the occasional stray var that than make the mistake of crafting an array of important static data only to lose it because of an oversight.

**Comment by aplteam** [comment]
> As to the idea of *SetChanged* never saving even named vars without
*Variables←'On'* I'd rather have to erase the occasional stray var that
than make the mistake of crafting an array of important static data only to
lose it because of an oversight.

Fine. Bute why would you not have vars=on then? I don't get it.

You can actually achieve what you want. I can't because the behaviour is
inconsistent. That seems wrong to me.

**Comment by PhilLast** [comment]
If I create a project using defaults then spend half an hour creating a text array in the editor then log off I've wasted half an hour.

If I create a project using defaults then copy and add a namespace without checking whether it contains any stray variables of which I am previously unaware I can erase them.

Whichever way this falls there will be easy routes to correct any problems arising. As things stand everything is as described in the ocumentation.

**Comment by PhilLast** [comment]
After a long off-line discussion with Kai on this topic with both parties throwing up examples and counter examples I'd like to put forward this mutually agreed proposal.

_CreateProject_ will continue only  to add existing variables from the project space to _APLSource_ if the _-Variables=On_ option is set.

But whereas the value of that option is currently preserved as the homonymous configuration parameter _Variables←On|Off_ no such config parm will be created or recognised subsequently.

Editing a previously unsaved var will always be ignored as there will be nothing to tell acre to add it. This will solve the problem of inadvertently saving edited local variables from the tracer.

_SetChanged_ and _EditArray_ really will be the only ways to add new vars to an existing project and they will always do it as there will be nothing to tell them not to.

Editing a variable that already has an associated _.apla_ or _.char*_ file will continue to cause the new value to be saved.

**Please indicate your pros or cons asap.**

**Comment by e9gille** [comment]
I started this reply this morning, but kept getting interrupted throughout the day so haven't managed to complete this until now. As I type this I see another message from Phil, so will post this as is and reflect on his message.

As Kai points out, I argued against saving arrays automatically unless explicitly saved. The reason was that—unlike functions—an array is typically variable and should therefore not be stored. Variables got saved to disc accidentally when I traced code and found myself editing variables to test edge conditions. Having the option to turn off the tracking of variables on a project level I think is great.

I haven't used the SetChanged command on a namespace, so I'm not sure what the scenario is. SetChanged is a command to flag items that would otherwise be overlooked due to them being changed outside the editor. If you use tools that change a large number of items in your project and you want to trigger acre to do its business then I agree with Kai that it should consistently ignore variables if tracking of them has been turned off for the project.

If the scenario is as Phil suggests, that you extend the project by copying a namespace from elsewhere that you'd like to add, then I can see that you may want to add arrays as well for that space.

**Comment by PhilLast** [comment]
Changes are ready to commit and push.

The only differences you'll see are 
* the **-variables=** *option* of **CreateProject** will no longer be saved as the **Variables** *config parm*
* existing projects with _redundant_ config parm **Variables On** will cease to save *new* vars added via the editor
* a message _"Not saved - fqn - use SetChanged"_ will be issued instead

**SetChanged** and **EditArray** will continue to add new vars.
Previously saved vars will continue to be saved when changed in **)ED** and **⎕ED**.

**Comment by aplteam** [comment]
Decided: by design
