### ISSUE TITLE
In 18.0, making use of acre's OnAfterSave option crashes SALTUtils

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#222]
My setup.dyalog contains this statement:

```
{}⎕se.acre.AfterSave '⎕SE.OnAfterSave'
```
In 18.0 this makes SALTUtils crash on line 1020, which is line [16] of the "Hook" function.

Obviosly the new hooking mechanism introduced in version 18.0 works fine for the "Fix" event but not at all for the "AfterFix" event.

This might need collaboration with Dyalog to get fixed.

**Comment by PhilLast** [comment]
Do you mean the call to `⎕SE.acre.AfterSave` itself causes the crash or subsequent edits?

Can you send Session output )SI etc.

**Comment by PhilLast** [comment]
Of the above four bullet points I have done all but the third. SALTUtils.EditorFix is only invoked when the edited item is not within any tracked acre project.

In other words I have done as little as possible merely reverting to what is essentially the same behaviour that has been current since acre 3 which is hardly different from acre 1.

I should like to implement Dyalog's interface but will await guidance.
