### ISSUE TITLE
]acre.OpenProject crashes

### ISSUE THREAD

**Issue by mbaas2** [the-carlisle-group/Acre-Desktop#232]
I am attempting to open a local clone of https://github.com/steveman7/TamStat

```
]ACRE.OPENPROJECT c:\git\tamstat\     #.TamStat
Problem reading c:/git/tamstat/acre.config
DOMAIN ERROR
openProject[8] cfg←(dft←configFields'')readConfig dat.config ⍝ #171 SV.config
                                       ∧
                    ]acre.version
┌────┬─────────┬──────────┬─────┐
│Acre│8.2.0+323│2020-06-11│16:30│
└────┴─────────┴──────────┴─────┘

```

**Comment by PhilLast** [comment]
Hey Michael

Acre is supposed to fail in the event of an invalid config file[i] with either
**Command Execution Failed: Cannot ascertain encoding of** _filename_
(the file must start with "{" (JSON), ":Namespace" (APLSCRIPT) or "[" (APLAN)[ii] with JSON as default) 
or 
**Command Execution Failed: Problem reading** _filename_
(the content is invalid for the encoding, whichever it is)

If you have `]udebug on` it will stop at the point of error as above due to the overriding of the trapping in **⎕SE.UCMD**. 

[i] If there is no file called "acre.config" acre will continue with defaults for all config parameters.
[ii] at some time in the future this may be replaced with Dyalog's dialect of array/space notation _when implemented as a part of the interpreter_; or dropped altogether.

Phil

**Comment by PhilLast** [comment]
@norberturkiewicz  has discovered a problem with ⎕JSON in latest build that might explain this.

I'll investigate tomorrow

**Comment by PhilLast** [comment]
_Omission_: "... latest **_Dyalog_** build ..."

**Comment by PhilLast** [comment]
Latest commit and push
```
      ]acre.version
 Acre  8.2.0+331  2020-10-04  21:27 
```
now contains a workaround for **⎕JSON**'s failure to accept a _charmat_ argument on import which problem I have reported to Dyalog support.

**Comment by mbaas2** [comment]
Thanks - it works now!
