### ISSUE TITLE
Latest release broke 14.0 OpenProject

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#237]
]acRE.version
 Acre  8.2.0+334  2020-12-08  13:08 
      ]acRE.openproject c:\github\cas-6.0
* Command Execution Failed: DOMAIN ERROR
       ]udebug on
Was OFF
      ]acRE.openproject c:\github\cas-6.0
DOMAIN ERROR
space[2] r←⊃,/⍺⍺ ⍵.{'⋄',⍵,'←',⍺ ⍺⍺⍎⍵}/⍺,⍪~∘' '¨↓⍵.⎕NL 2.1 9.1
          ∧

I get this popup now.

![image](https://user-images.githubusercontent.com/5807754/101679079-7587cd80-3a24-11eb-8b7c-d7e31c46e934.png)

**Comment by norberturkiewicz** [comment]
Downgrading to Acre 8.2.0+324 2020-07-01 11:57 fixed the open issue.

**Comment by PhilLast** [comment]
I missed this because I was just looking at the lastest amend times and I guess you posted this soon after my last post to #235 on the same day.

Looking now,

Can you say what Dyalog version you're using?

**Comment by norberturkiewicz** [comment]
14.0.37905

**Comment by PhilLast** [comment]
The function _space_ that gave the error was last changed 27 April this year.
The function _encode_ that called it was last changed 30 Oct 2018. 

Neither change could have caused this error which must have been waiting to bite since I failed to proof it against an empty argument to catenate reduction when acre was backfed to v14.0 and v14.1. Dyalog first implemented catenate reduction on empty in v15.0.
```
      ,/(s,0)⍴⍵ ←→ s⍴⊂0/⊃⍵
      ,⌿(0,s)⍴⍵ ←→ s⍴⊂0⌿⊃⍵
```
I'm surprised it worked after you reverted to 8.2.0+324 unless other things changed in the interval such as adding a new item.

There are 89 instances of (,/) in acre. I only proofed those that caused an error in the initial testing and a very few that have surfaced since.

Will attack this one now.
