### ISSUE TITLE
Is CaseCode base-16 or base-8?

### ISSUE THREAD

**Issue by abrudz** [the-carlisle-group/Acre-Desktop#238]
I seem to remember that during the Link-Acre "hackathon" we decided on using base-8, since this is directly convertible from binary (without precision problems, since 3 bits map to 1 digit) while avoiding potential case clashes in the case code itself.

Link uses base-8, but it seems that Acre and its documentation still use base-16. What are the plans?

**Comment by PhilLast** [comment]
Yes it is hex. I believe the propeties you site apply also to hex but with codes slightly shorter: **⌈dec×3÷4**; and the expression
```
16|(⎕D,'abcdef',⎕D,'ABCDEF')⍳c
```
to ensure both small letters and capitals in the code map to the same mask.

But you are correct, we did agree to change as it was decided that the reduction in potential confusion by all digit code outweighed the extra length.

Unfortunately the change that would require a conversion of all existing projects was never scheduled and since then acre has been deemed to be complete and development has ceased.

**Comment by abrudz** [comment]
OK, but now what do we do? This makes Link and Acre mangle each others' file case coded names, leading to value errors for variables and unscripted namespaces (the only items not knowing their own name) since APL is case sensitive.

Do we need to add an "ignore case code" option to both Link and Acre? Or an option to use the other's case code format? Or use heuristics to attempt at determining the case code format in use?

The whole point of case coding was to make case insensitivity a non-issue, and the current situation just makes it much worse by consistently *forcing* an issue where, without case codes, the probability of an issue was very low.

Also, what does "development has ceased" mean? Will bugs not be fixed? Will no features ever be added?

**Comment by PaulMansour** [comment]
If you want Link to be compatible with Acre, change Link.

**Comment by aplteam** [comment]
Does this mean acre is now abandonware?

**Comment by PaulMansour** [comment]
> Does this mean acre is now abandonware?

No it does not. As you know, a tremendous amount of time and money has been put into Acre.  It is critical to the daily operations of the Carlisle Group. It is maintained and enhanced as necessary. A look at the issue, release, and commit history should confirm that.  At this point, however, we do not wake up every morning and add features to Acre. We have no pressing to-do list.
