### ISSUE TITLE
Changing an Item in the OS

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#25]
Editing an item in the OS, and then attempting to open the project, fails.:

```
       ]aCRE.Openproject c:\APLProjects\dfnNotes   
Opening  from c:/APLProjects/dfnNotes/
 into #.notes
327 items loaded  from c:/APLProjects/dfnNotes/.acre/codefile
1 update imported  from c:/APLProjects/dfnNotes/APLSource/
* Command Execution Failed: FILE NAME ERROR
```

**Comment by PhilLast** [comment]
Acre is just opening the project so none of it exists.
It's recognised a file has changed so has read it in.
It's parsed the filename so it has the information it needs to create a changefile.
The function that puts together the filename only gets the fqn which is sometimes enough because it's already in the ws.
But the item doesn't exist yet so it doesn't know its type and puts '.*'.
(That's so that ]Restore can use ⎕NINFO to find a deletefile)
The '.*' was being ignored and it tried to write the changefile with that in it's name.

Fixed
