### ISSUE TITLE
Creating Project when Folder Already Exists

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#4]
If the folder already exists, and it looks like a project folder (that is, it contains an APLSource sub folder), then we get:

~~~
       ]aCRE.Createproject 'c:\APLProjects\VarTest'
The folder already contains a project - use OpenProject
~~~

The folder IS the project, so I think this error message error message should be more like "Project already exists."

If the folder exists but is empty or contains random stuff then Acre goes ahead and converts the folder  into a project folder. How do we feel about this?

I'm leaning towards saying that CreateProject should insist that the project folder does not exist.

**Comment by PhilLast** [comment]
It's currently based entirely on the existence of any of the three `APLSource/ | .acre/ | acreconfig.txt` _within_ the project folder.
The decision about whether to proceed within the two functions could be made earlier if it were based only on the existence of the project folder.
At one time a few weeks ago I was considering having only one - OpenProject - as it already does almost everything create does. I didn't because of the possibility of screwing up the wrong folder.
Only remains for someone to decide what the messages should be. Currently:
```
Invalid path or not a project - use CreateProject
The folder already contains a project - use OpenProject
```

**Comment by PaulMansour** [comment]
Definitely need the two commands as you have it.

But  the messages are inconsistent, as the first one considers a project to be "a" folder, while the second one  considers a project to "in" a folder.

I would also remove the phrases  "- use CreateProject" and "- use OpenProject", as these are directing the user to do something he probably does not want to do.  If you are trying to open an existing project and you have the path invalid or incorrect, you will want to change the path, not use CreateProject. Conversely, if you are trying to create a project over another project, you probably want to delete the existing project or create an entirely new project, not open one.

Therefore I would have  the error messages for Open and Create be:
~~~
Invalid path or not a project.
Project or folder already exists.
~~~

The latter implying that the folder must not exist on CreateFolder - that a generic folder is not converted into a  project folder.

**Comment by aplteam** [comment]
@PhilLast ?

**Comment by PhilLast** [comment]
Fixed
