### ISSUE TITLE
]acre.stats output?

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#43]
What is the output supposed to be from ]acre.stats?

]openproject c:\github\acre-desktop
Opening  from c:/github/acre-desktop/
 into #.acre
397 items loaded  from c:/github/acre-desktop/.acre/codefile
#.acre
]stats
Project not open

The result is from Acre-Desktop 4.0.4

**Comment by PhilLast** [comment]
```
      ]projects
 #.dfns  C:/Users/Phil/Desktop/acre4 projects/dfns/ 
 #.acre  C:/Users/Phil/Desktop/acre4 projects/acre/ 
      ]stats dfns
.--------------------------------------.
| When opened:     2018-01-24 11:30:47 |
| Time to load:                     1s |
|                                      |
| Variables                        612 |
| Functions                        203 |
| Operators                         61 |
| Scripts                            0 |
| Classes                            0 |
| Interfaces                         0 |
|                                      |
| Total items:                     876 |
| in 6 namespaces                      |
'--------------------------------------'
      ]stats acre
.--------------------------------------.
| When opened:     2018-01-24 11:30:55 |
| Time to load:                     1s |
|                                      |
| Variables                          4 |
| Functions                        311 |
| Operators                         81 |
| Scripts                            1 |
| Classes                            0 |
| Interfaces                         0 |
|                                      |
| Total items:                     397 |
| in 9 namespaces                      |
'--------------------------------------'
```

**Comment by PhilLast** [comment]
for any command:
```
      ]?stats
Command "acre.Stats".                                    
                                                         
 Project Statistics                                      
 Syntax: ]Stats project                                  
                                                         
Script location: "C:\Users\Phil\Desktop\acre\acre.dyalog"
```

**Comment by norberturkiewicz** [comment]
I guess the confusion came from the error message.  "Project not open" wasn't too helpful with a blank input.

 Syntax: ]Stats project

First I tried putting the full path to the project.  Trial and your example showed that I need to use the project namespace name to get results.

**Comment by PaulMansour** [comment]
Don't forget to check the wiki documentation! I think it is actually close to being correct and up to date!

**Comment by PhilLast** [comment]
I have the syntax for each command available. I'll see if I can add them as error msg if commands are used wrongly. I think I already do that for CreateProject. Trouble is it's not Stats that's giving that message but the operator that decides which project it's going to give to it. Stats didn't get called because there wasn't one. But by then I know what the command's called so it should be fairly easy. In fact easier because I only have to do it in one place for all Project commands. And maybe Item commands too.

**Comment by PhilLast** [comment]
> aplteam assigned PhilLast 10 hours ago

Can someone tell me what that means?

**Comment by aplteam** [comment]
It means that it becomes meaningful for you to use the filter "Your issues" in order to see just the issues assigned to you rather than all of them.
Also, since Paul agreed, an enhancement that is not assigned to anybody (yet) is a discussion but as soon as it is assigned (usually to you) then it's decided and needs implementing.

**Comment by PhilLast** [comment]
Fixed
