### ISSUE TITLE
StartUp fails silently

### ISSUE THREAD

**Issue by aplwiki** [the-carlisle-group/Acre-Desktop#47]
I made a typo when specifying a function call on "StartUp" in acreconfig.txt.

Acre does not tell; it should.

**Comment by PhilLast** [comment]
Reread the spec last evening. I'm wrongly assuming it should ececute in # rather than the project space and on LoadProject as well as OpenProject.

Will execute only for "main" project not "dependants", in the project space and only when Opened.
Will also display the ⎕DM on error but terminate normally.

**Comment by aplteam** [comment]
Fixed.
