### ISSUE TITLE
LENGTH ERROR opening project

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#65]
]openproject c:\github\tcgutilities
 Acre  4.0.6  2018-02-02
Opening  from c:/github/tcgutilities/
 into #.CarlisleGroup.Utilities
* Command Execution Failed: LENGTH ERROR
[TCGUtilities.zip](https://github.com/the-carlisle-group/Acre-Desktop/files/1717247/TCGUtilities.zip)

**Comment by PhilLast** [comment]
I can open the project but the APLSource folder is empty. I hit and fixed this bug at my end soon after release. It only affects empty projects. Obviously should have pushed it up straight away. Current workaround - put a file `f-0.function` - into APLSource with content: `f` and reopen the project.
I could push my current version of the code but it's largely broken at the moment while I'm removing the codefile while hoping that I don't have to put it back because of poor performance.

**Comment by aplteam** [comment]
Fixed.
