### ISSUE TITLE
!!!Not fixed error

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#70]
]openproject c:\github\cas7
 Acre  4.0.6  2018-02-02
! Invalid path or not a project. c:/github/Conga/
Opening  from c:/github/AcreTools/
 into #.CarlisleGroup.AcreTools
13 items loaded  from c:/github/AcreTools/.acre/codefile
Loading  from c:/github/Rumba/
 into #.CarlisleGroup.Rumba
495 items loaded  from c:/github/Rumba/.acre/codefile
40 updates loaded  from c:/github/Rumba/.acre/changes/
Opening  from c:/github/cas7/
 into #.CAS
10907 items loaded  from c:/github/cas7/.acre/codefile
5 updates loaded  from c:/github/cas7/.acre/changes/
!!! Not fixed:
 #.CAS.PDFTOOLS.ViewPDF.OpenInNewRenderer
#.CAS

**Comment by PhilLast** [comment]
There are basically two possible reasons. 

1. If its a fn or op it might have fixed under another name than that indicated by the filename.
2. There's something wrong with the definition that prevents APLAN.decode, ⎕FX or ⎕FIX finishing the task. These can include an error in the APLAN notation; anything for which the editor issues the "Can't fix" message; or a missing dependency in the class-tree. Acre's try, try, try again method of fixing the class-tree terminates when an iteration fails to fix anything at all to avoid falling into an endless loop.

Can you send the source file?

**Comment by norberturkiewicz** [comment]
The source file does not exist for

 !!! Not fixed:
 #.CAS.PDFTOOLS.ViewPDF.OpenInNewRenderer

![image](https://user-images.githubusercontent.com/5807754/36488412-024356fc-16e9-11e8-8c84-c53bbc773b4a.png)

I do remember doing a ) or ]erase on the misspelled function to get the right one in there.  I have a copy of the project that will reproduce the issue if you want.

**Comment by PhilLast** [comment]
My above explanation relies on the fact that I no longer have a codefile.

Obviously because I still haven't managed to push 4.1.0 you still have one which is keyed on the item name and keeps all items until ]purgehistory is run. Some combination of that and the merge of codefile, sourcetree, changefiles and deletefiles must be causing the effect. The fact that the name "...Renderer" appears in the session and "Rendered" in the folder must mean the former is coming from either the codefile or the change or deletefile.

I assume you have "...Rendered" in the ws unless the content of the file says something else. If both fns have/had the same definition I suggest you ensure both exist by amending what you have in the editor then ]purgehistory if you don't mind losing your changefiles (which I think I can safely assume you don't). Then ]erase the one you don't want.

I'm loth to go too deeply into this issue because 4.1.0 is so different in the parts of the code that affect it that I feel I'd be wasting your time and mine.

**Comment by norberturkiewicz** [comment]
I figured it was a sync issue and not too worried about it with the upcoming release.
