### ISSUE TITLE
⎕ vars not getting set properly on nix interpreter

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#84]
@PhilLast and @aplteam  I think you were going to investigate the issue of the workspace  fixing differently on nix vs Windows.  This is now becoming apparent it's a big problem.  Can we move this to the priory list?

**Comment by PhilLast** [comment]
I need to change the fixing order in any case and this might well fix the problem whatever is causing the difference.

**Comment by aplteam** [comment]
It's different between Linux and Windows indeed. I did not bother to check the Mac because obviously when you need a sorted list you have to make sure yourself that it is identical on all platforms.

At least for the time being: I am going to report this as a bug.

The attached WS contains `Linux` and `Windows` with hold the result of `⎕NL⍳16`.

[Sort.zip](https://github.com/the-carlisle-group/Acre-Desktop/files/1856478/Sort.zip)

**Comment by PhilLast** [comment]
How are they different apart from the lack of "Windows" in Windows?
Incidentally did you expect anything beyond ⎕NL 9.7?

**Comment by aplteam** [comment]
Sorry, I defeated myself. I assigned the result of `⎕NL⍳16` to `Windows`, saved the WS, transferred it to Linux and assigned the value to `Linux` and compared the two with `≡` and, surprise, they are different.

They are not. Which is bad news as it means that we don't understand why it did go wrong in the past, right?

In principle the right argument of `⎕NL` can be anything from 1 to 15. Back in the days when there were no namespaces I used `⎕nl 2 3 4`. Then 9 was introduced and I had to change all these statements. I am never doing this again!

**Comment by PhilLast** [comment]
v4.2.0 includes a change to the fixing the project's namespace tree in the order of fqn length. So that any script can set the environment through assignment to ##.⎕whatever before its children the parent of each script is created immediately prior to the fixing of the script itself. The rest of the tree is then created within the branches already formed.

If the the attempt to open the same project in different OSs is made again my guess it that it will work this time whatever the reason it didn't work before.

I hope this issue could then be closed.

**Comment by PhilLast** [comment]
Should be fixed. Please reopen if problems persist.

**Comment by PhilLast** [comment]
I don't seem to have access to CAS7 on github but have an old copy of it. If I understood correctly the problem of order of fixing was causing the more serious problem of quad variables not being set correctly.

I don't know if that problem has gone away but in my old copy of CAS I just noticed that there are 35 files in and below APLSource called "QuadVariables-11" with not a file extension among them. Because it was mooted that users might want to keep other files in the same folders as the sourcefiles acre merely reads the files with recognised file extensions and ignores the rest. In consequence if I open CAS7 not a single 'QuadVariables' script appears.

If the same is true of your copy, renaming each one as "QuadVariables-11.script" _should_ settle the issue.

**Comment by PhilLast** [comment]
Is this still a problem?

**Comment by PhilLast** [comment]
@norberturkiewicz  If you followed the above advice or if the problem has gone away for some other reason could you close this issue? 
If you ignored the advice re. renaming __"QuadVariables-11"__ to __"QuadVariables-11.script"__ and if you have already moved to __v4.8.1.036__ the names should change to __"QuadVariables-11.apln"__

**Comment by norberturkiewicz** [comment]
I haven’t tested on Linux recently due to other issues where the interpreter simply “goes away” on Linux when using Conga/Rumba.   I’ll make it a priority to setup that environment again.

**Comment by PhilLast** [comment]
Kai, you forgot:
* intrepretre
* intrepertre
* interpretre
* interpretre

**Comment by aplteam** [comment]
Thanks for pointing that out ;)

It wasn't actually me: the GitHub website had a latency problem. My typing seemed to have the intended effect with a delay, but when I pressed "Save" it changed again. It took me two circles to realize that it was not my mistake but that I was too fast, or rtaher that I believed what I was looking at. Seems that these days you shouldn't.
