### ISSUE TITLE
nameclass

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#93]
```
      'nameclass'⎕SE.acre.run '#.objectname'
```
returns the name class of `#.objectname` if it exists in the current WS and `.*` if it doesn't.

I would like to get a matrix with two columns in case the right argument is empty: all name classes with

`[;1]` = name class (`.function`, `.operator`, ...)
`[;2]` = description ("Function", "Operator", ...)

If you think that a vector of text vectors would suffice: yes it would, but if we ever settle for a aplf, aplo etc. then the user would probably appreciate a more verbose result.

**Comment by PhilLast** [comment]
Your suggested empty argument could equally be passed as a genuine empty list of itemnames under program control but would probably cause an error in the caller.

As all calls to `acre.run` are outside the normal command structure there's no provision for help.

If a '?' as right argument would do instead of the empty argument then the same protocol could prompt all of them to produce an explanation of some sort.

**Comment by aplteam** [comment]
Okay, that's good.

**Comment by PhilLast** [comment]
Implemented some weeks ago
