### ISSUE TITLE
Do not rely on length of editFix's argument

### ISSUE THREAD

**Issue by mbaas2** [the-carlisle-group/Acre-Desktop#94]
I just did a few steps in AD and through my fooling around came into a state where I had ]loaded a fn into # of a ws that a ns which used acre. After editing my fn editFix crashed

LENGTH ERROR
editFix[15] (editor event value space name new)←⍵             ⍝ so long as onFix unchanged
                                               ∧

      ≢⍵
7 

I suggest a 6↑ there...

**Comment by PhilLast** [comment]
Thanks Michael
Notice the comment in the line in error. It turns out that the `onFix` event certainly has changed after ten years. 
Kai pointed this out to me with respect to Dyalog version 17. Your suggested change is in the next version ready for release (almost):
`editFix[15] (editor event value space name new)←6↑⍵ ⍝ so long as onFix unchanged`

**Comment by PhilLast** [comment]
Fixed
