### ISSUE TITLE
Change files, source files, delete files and item names

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#96]
Since I have recently released the `]CodeBrowser` I'd come to realize how valuable such a tool is when it comes to code reviewing.

I want something similar for reviewing changes that are due to be committed. There is a problem however.

Where do I start from: obviously with the change files and the delete files, because anything that was deleted since I've started working is not available in `APLSource\`.

In order to create a source filename via the designated acre method I need the fully qualified name of the object in the APL workspace. But the `itemname` method requires a source filename as input, **not** a change filename or a delete filename.

I am stuck.

**Comment by PaulMansour** [comment]
Maybe not obviously from the change files if you are using git

Sent from my iPhone

On May 8, 2018, at 6:55 AM, APL Team Ltd <notifications@github.com<mailto:notifications@github.com>> wrote:


Since I have recently released the ]CodeBrowser I'd come to realize how valuable such a tool is when it comes to code reviewing.

I want something similar for reviewing changes that are due to be committed. There is a problem however.

Where do I start from: obviously with the change files and the delete files, because anything that was deleted since I've started working is not available in APLSource\.

In order to create a source filename via the designated acre method I need the fully qualified name of the object in the APL workspace. But the itemname method requires a source filename as input, not a change filename or a delete filename.

I am stuck.

**Comment by aplteam** [comment]
I've looked into it. I expected git to save the versions somewhere obvious. After that starting from the change files seemed to be very obvious ;)

I propose a method `filename` which takes the name of an APL object (which may or may not exist) and returns just the filename part (= no folder) without the type and without requiring any project to be open.

**Comment by aplteam** [comment]
I want the name without the need for it to be part of an open APL project. "." or "/" I don't mind because they can converted with ease.

**Comment by PhilLast** [comment]
So do you mean just the name with the case codes added as quoted above?

**Comment by PhilLast** [comment]
Assuming that that _is_ what you want how about a hook `'casecode'` [say] that encodes and adds the case codes for an argument that doesn't contain any hyphens and decodes and removes them for one that does. So that extending the above example either would lead to other:
```
'alpha.Bravo.CHarley'       → 'alpha-0.Bravo-1.CHarley-3'
'alpha-0.bravo-1.charley-3' → 'alpha.Bravo.CHarley'
```

**Comment by aplteam** [comment]
That would do, yes.

**Comment by PhilLast** [comment]
Implemented
