### ISSUE TITLE
Open into endless loop on dependencies that rely on one another

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#97]
Acre 4.3.0

I have two projects that both open one another and the same dependencies.  With this structure Acre goes into a continuous open/reopen loop

project 1 config

:Namespace 
    CaseCode←'On'
    KeepHistory←'Off'
    Open← 'AcreTools' 'Rumba' 'CASFile' 'TCGUtilities'  'CASDataModels' 'CAS7'
    ProjectSpace←'#.CarlisleGroup.CFS' 
    StartUp←'#.CarlisleGroup.CFS.v1.StartTestServer 0'
:EndNamespace 

project 2 config

:Namespace
    CaseCode←'On'
    Open←'Rumba' 'CASFile' 'TCGUtilities' 'CAS-File-Server' 'CASDataModels'
    ProjectSpace←'#.CAS'
    StartUp←''
    KeepHistory←'Off'
:EndNamespace

![2018-05-10_14-56-09](https://user-images.githubusercontent.com/5807754/39891093-57d2fa30-5462-11e8-83f1-ce7d7d4d29b7.gif)

**Comment by PhilLast** [comment]
I believe this is correct. Five projects `'one'` `'two'` `'three'` `'four'` and `'five'`.
All open into homonymous spaces by default.
`one` has `    Open←'three' 'four' 'two' 'five #.six'`
`two` has `    Open←'one' 'two' 'three' 'four' 'five'`
The others have no dependencies.
Note that `one` opens 'five' into `#.six` and `two` specifies itself.
Before attempting to open a project the argument is appended to a buffer so that it won't be attempted again. The buffer is cleared at the start of each command.
```
      ]openproject one
Opening from C:/Users/Phil/Desktop/acre4projects/three/
 to #.three
Please wait - Reading 1 file from C:/Users/Phil/Desktop/acre4projects/three/APLSource/
Opening from C:/Users/Phil/Desktop/acre4projects/four/
 to #.four
Please wait - Reading 1 file from C:/Users/Phil/Desktop/acre4projects/four/APLSource/
Opening from C:/Users/Phil/Desktop/acre4projects/five/
 to #.five
Please wait - Reading 1 file from C:/Users/Phil/Desktop/acre4projects/five/APLSource/
Opening from C:/Users/Phil/Desktop/acre4projects/two/
 to #.two
Please wait - Reading 1 file from C:/Users/Phil/Desktop/acre4projects/two/APLSource/
Opening from C:/Users/Phil/Desktop/acre4projects/five/
 to #.six
Please wait - Reading 1 file from C:/Users/Phil/Desktop/acre4projects/five/APLSource/
Opening from C:/Users/Phil/Desktop/acre4projects/one/
 to #.one
Please wait - Reading 1 file from C:/Users/Phil/Desktop/acre4projects/one/APLSource/
#.one
```
Opening `one` opens `three` then `four` then starts to open `two` but `two` opens `five` (but _only_ `five`) after which `two` is opened then `one` re-opens `five` but into `#.six` so there are two copies of it then `one` is itself finally opened.

**Comment by PhilLast** [comment]
Fixed several weeks ago
